# Generated by Django 6.0.4 on 2026-04-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('order_placed', '🛒 New Order Placed'), ('order_updated', '📦 Order Status Updated'), ('registration', '👤 New User Registered'), ('partnership', '🤝 Partnership Request'), ('contact', '📩 New Contact Inquiry'), ('sell_order', '💰 Avon Points Sell Order'), ('insurance', '🛡️ Insurance Request'), ('brokerage', '📈 Brokerage Account Request'), ('training', '🎓 New Enrollment'), ('kyc', '🪪 KYC Submission'), ('general', '🔔 General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
