# Generated by Django 6.0.4 on 2026-06-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_rate', models.DecimalField(decimal_places=4, default=0.01, help_text='End-user/consumer reward as a decimal — e.g. 0.0100 = 1%', max_digits=6, verbose_name='Consumer Reward Rate')),
                ('referral_rate', models.DecimalField(decimal_places=4, default=0.025, help_text='Reward for referring a buyer as a decimal — e.g. 0.0250 = 2.5%', max_digits=6, verbose_name='Referral Reward Rate')),
                ('payment_days', models.IntegerField(default=45, help_text='Number of days after purchase before the loyalty reward is processed', verbose_name='Payment Processing Day')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty Settings',
                'verbose_name_plural': 'Loyalty Settings',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('order_placed', '🛒 New Order Placed'), ('order_updated', '📦 Order Status Updated'), ('registration', '👤 New User Registered'), ('partnership', '🤝 Partnership Request'), ('contact', '📩 New Contact Inquiry'), ('sell_order', '💰 Loyalty Points Withdrawal'), ('training', '🎓 New Enrollment'), ('kyc', '🪪 KYC Submission'), ('general', '🔔 General')], default='general', max_length=30),
        ),
    ]
