# Generated by Django 6.0.4 on 2026-06-24 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loyaltysettings_alter_notification_notif_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown on the blog listing page.', max_length=400)),
                ('content', models.TextField(help_text='Full article content. HTML is supported.')),
                ('category', models.CharField(choices=[('trade_news', '📰 Trade News'), ('coffee_market', '☕ Coffee Market'), ('import_tips', '🚢 Import & Export Tips'), ('east_africa', '🌍 East Africa'), ('regulations', '⚖️ Regulations & Compliance'), ('company_news', '🏢 Company News')], default='trade_news', max_length=30)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('cover_image_url', models.URLField(blank=True, help_text='Stock photo URL used if no image is uploaded.')),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in the featured slot at the top of the blog.')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
