# Generated by Django 6.0.4 on 2026-07-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_update_loyalty_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('consent', models.BooleanField(default=True)),
                ('subscribed', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='consumer_rate',
            field=models.DecimalField(decimal_places=4, default=0.005, help_text='End-user/consumer reward as a decimal — e.g. 0.0100 = 1%', max_digits=6, verbose_name='Consumer Reward Rate'),
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='referral_rate',
            field=models.DecimalField(decimal_places=4, default=0.01, help_text='Reward for referring a buyer as a decimal — e.g. 0.0250 = 2.5%', max_digits=6, verbose_name='Referral Reward Rate'),
        ),
    ]
