# Generated by Django 6.0.4 on 2026-04-15 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('coffee', 'Coffee'), ('pharmaceuticals', 'Pharmaceuticals'), ('agriculture', 'Agriculture'), ('textiles', 'Textiles'), ('machinery', 'Machinery'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('quantity_available', models.IntegerField(default=0)),
                ('unit', models.CharField(default='unit', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('video_url', models.URLField(blank=True)),
                ('market_type', models.CharField(choices=[('local', 'Local'), ('international', 'International'), ('both', 'Both')], default='both', max_length=20)),
                ('origin_country', models.CharField(blank=True, max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_type', models.CharField(choices=[('express', 'Express'), ('ordinary', 'Ordinary')], default='ordinary', max_length=10)),
                ('destination_country', models.CharField(max_length=100)),
                ('destination_address', models.TextField()),
                ('desired_arrival_date', models.DateField()),
                ('desired_arrival_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('accepted', 'Accepted'), ('not_accepted', 'Not Accepted'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('referred_by', models.CharField(blank=True, max_length=200)),
                ('referrer_unique_id', models.CharField(blank=True, max_length=50)),
                ('avon_points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
