# Generated by Django 6.0.4 on 2026-06-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reward_payment_date',
            field=models.DateField(blank=True, help_text='Automatically set to 45 days after purchase', null=True, verbose_name='Reward Payment Due Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender_target',
            field=models.CharField(choices=[('all', 'All'), ('men', 'Men'), ('women', 'Women'), ('children', 'Children')], default='all', max_length=10, verbose_name='Target Audience'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avon_points_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Loyalty Points Earned'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('shoes', 'Shoes'), ('watches', 'Watches'), ('coffee', 'Coffee')], max_length=50),
        ),
    ]
