# Generated by Django 6.0.4 on 2026-06-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_order_paid_at_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Stock/placeholder photo link — used only if no photo is uploaded above.'),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, help_text='Upload your own product video — takes priority over Video URL below.', null=True, upload_to='products/videos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload your own photo — takes priority over Image URL below.', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo link — used only if no video is uploaded above.'),
        ),
    ]
