# Generated by Django 6.0.4 on 2026-06-21 17:09

from django.db import migrations, models


def reassign_children_rows(apps, schema_editor):
    # 'children' is no longer a valid Target Audience choice. These rows are
    # already inactive (deactivated in the earlier catalog cleanup), so this
    # is just data hygiene — reassign rather than leave a now-invalid value.
    Product = apps.get_model('marketplace', 'Product')
    Product.objects.filter(gender_target='children').update(gender_target='all')


def reverse_reassign_children_rows(apps, schema_editor):
    # Not reversible (original 'children' tagging isn't recoverable) — no-op.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_update_product_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender_target',
            field=models.CharField(choices=[('all', 'All'), ('men', 'Men'), ('women', 'Women')], default='all', max_length=10, verbose_name='Target Audience'),
        ),
        migrations.RunPython(reassign_children_rows, reverse_reassign_children_rows),
    ]
