# Generated by Django 6.0.4 on 2026-08-05 11:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_add_bulk_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload photo — stored on Cloudinary CDN.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
