# Generated by Django 6.0.4 on 2026-08-09 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_product_image_cloudinaryfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCountryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Canada', 'Canada (CAD)'), ('USA', 'USA (USD)'), ('Uganda', 'Uganda (UGX)'), ('Kenya', 'Kenya (KES)'), ('Netherlands', 'Netherlands (EUR)'), ('Japan', 'Japan (JPY)')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('UGX', 'UGX'), ('KES', 'KES'), ('EUR', 'EUR'), ('JPY', 'JPY')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_prices', to='marketplace.product')),
            ],
            options={
                'ordering': ['country'],
                'unique_together': {('product', 'country')},
            },
        ),
    ]
