# Generated by Django 6.0.4 on 2026-08-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_add_display_currency_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange_rate_used',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Rate at time of checkout', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='display_currency',
            field=models.CharField(blank=True, default='CAD', help_text='Currency chosen by buyer at checkout', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='display_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Total in buyer's chosen currency", max_digits=14, null=True),
        ),
    ]
