# Generated by Django 6.0.4 on 2026-07-19 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_add_usd_forex_rates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('business_type', models.CharField(choices=[('registered_company', 'Registered Company'), ('small_business', 'Small Business / Shop'), ('individual', 'Individual'), ('organisation', 'Organisation / NGO')], max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('import', 'Import from T&TG — Buy our coffee'), ('export', 'Export to T&TG — Sell coffee to us')], max_length=10)),
                ('origin_country', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('coffee_type', models.CharField(choices=[('arabica', 'Arabica Green Coffee'), ('robusta', 'Robusta Green Coffee'), ('both', 'Both Arabica & Robusta'), ('artisanal', 'Artisanal Coffee Goods'), ('instant', 'Instant Coffee'), ('soap', 'Coffee-Based Soaps'), ('mixed', 'Mixed / Other')], max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('one_time', 'One-Time Shipment'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('casl_consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade Inquiry',
                'verbose_name_plural': 'Trade Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
