# Generated by Django 6.0.4 on 2026-07-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_add_trade_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeinquiry',
            name='agreement_document',
            field=models.FileField(blank=True, help_text='Signed agreement or supporting document', null=True, upload_to='trade_agreements/'),
        ),
        migrations.AddField(
            model_name='tradeinquiry',
            name='location_address',
            field=models.TextField(blank=True, help_text='Full physical address of the applicant'),
        ),
    ]
