# Generated by Django 6.0.4 on 2026-04-15 09:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('unique_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, choices=[('CA', 'Canada'), ('UG', 'Uganda'), ('NL', 'Netherlands'), ('US', 'United States'), ('KE', 'Kenya'), ('JP', 'Japan')], max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('national_id_front', models.ImageField(blank=True, null=True, upload_to='kyc/')),
                ('national_id_back', models.ImageField(blank=True, null=True, upload_to='kyc/')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='kyc/')),
                ('market_type', models.CharField(choices=[('local', 'Local Market'), ('international', 'International Market'), ('both', 'Both')], default='local', max_length=20)),
                ('user_role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('partner', 'Partner Company'), ('both', 'Buyer & Seller')], default='buyer', max_length=20)),
                ('term_preference', models.CharField(choices=[('short', 'Short Term'), ('long', 'Long Term')], default='short', max_length=10)),
                ('business_description', models.TextField(blank=True)),
                ('declaration', models.FileField(blank=True, null=True, upload_to='declarations/')),
                ('is_partner', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('partner_company', models.CharField(blank=True, max_length=200)),
                ('partner_id', models.CharField(blank=True, max_length=50)),
                ('has_certificate', models.BooleanField(default=False)),
                ('is_registered_company', models.BooleanField(default=False)),
                ('avon_points', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField(blank=True)),
                ('profile_link', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('website', models.URLField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AvonPointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn_purchase', 'Earned - Purchase'), ('earn_referral', 'Earned - Referral'), ('sell_order', 'Sell Order'), ('redeem_insurance', 'Redeemed - Insurance'), ('redeem_bills', 'Redeemed - Bills'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer to Trading'), ('invest', 'Investment')], max_length=30)),
                ('points', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quarter', models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('not_accepted', 'Not Accepted')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('min_execution_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
