# Generated by Django 6.0.4 on 2026-06-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avonpointtransaction',
            options={'verbose_name': 'Loyalty Point Transaction', 'verbose_name_plural': 'Loyalty Point Transactions'},
        ),
        migrations.AlterField(
            model_name='avonpointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earn_purchase', 'Earned — Purchase'), ('earn_referral', 'Earned — Referral'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avon_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='T&TG Loyalty Points'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, choices=[('CA', 'Canada 🇨🇦'), ('UG', 'Uganda 🇺🇬'), ('KE', 'Kenya 🇰🇪')], max_length=2),
        ),
    ]
