# Generated by Django 6.0.4 on 2026-06-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_avonpointtransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_withdrawal_limit',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verify_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customuser',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customuser',
            name='withdrawal_pin',
            field=models.CharField(blank=True, help_text='Hashed 4-digit PIN required for every withdrawal.', max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='withdrawal_pin_set',
            field=models.BooleanField(default=False),
        ),
    ]
