# Generated by Django 6.0.4 on 2026-07-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_usa_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avonpointtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('not_accepted', 'Not Accepted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, choices=[('CA', 'Canada 🇨🇦'), ('UG', 'Uganda 🇺🇬'), ('KE', 'Kenya 🇰🇪')], max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='withdrawal_pin',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
