# Generated by Django 6.0.4 on 2026-07-27 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sync_model_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cad_balance', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('usd_balance', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('ugx_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('kes_balance', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('eur_balance', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('jpy_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('conversion', 'Currency Conversion'), ('withdrawal', 'Withdrawal Request'), ('refund', 'Refund'), ('loyalty', 'Loyalty Points Conversion'), ('order', 'Order Payment'), ('admin', 'Admin Adjustment')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=300)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions_made', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
