# Generated by Django 6.0.4 on 2026-08-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saved_cart',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
