# Generated by Django 6.0.4 on 2026-09-26 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_create_role_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('earn', 'Points Earned'), ('redeem', 'Points Redeemed'), ('transfer', 'Points Transferred'), ('referral', 'Referral Bonus'), ('expire', 'Points Expired'), ('admin', 'Admin Adjustment')], max_length=20)),
                ('points_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('order_ref', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_po_user_id_b25d26_idx'), models.Index(fields=['action', 'created_at'], name='accounts_po_action_75e9e6_idx')],
            },
        ),
    ]
