# Generated by Django 6.0.4 on 2026-10-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_points_audit_log_and_cooloff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loyalty_cooloff_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
