# Generated by Django 6.0.4 on 2026-04-15 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('farming', 'Modern & Tech Farming'), ('enterprise', 'Corporate Mid-Market Enterprise'), ('financial', 'Financial Services & Investments')], max_length=20)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='training/')),
                ('video_url', models.URLField(blank=True)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('certificate_fee', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('is_free', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='tv/')),
                ('video_url', models.URLField(blank=True)),
                ('broadcast_schedule', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_live', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('certificate_requested', 'Certificate Requested'), ('certified', 'Certified')], default='enrolled', max_length=30)),
                ('progress_percent', models.IntegerField(default=0)),
                ('quiz_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('certificate_paid', models.BooleanField(default=False)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='training.trainingprogram')),
            ],
        ),
    ]
