# Generated by Django 6.0.4 on 2026-06-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='category',
            field=models.CharField(choices=[('farming', 'Modern & Tech Farming'), ('enterprise', 'Trade & E-Commerce'), ('trade', 'Import & Export Operations')], max_length=20),
        ),
    ]
