# Generated by Django 6.0.4 on 2026-07-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_add_program_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvprogram',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='External thumbnail URL (Unsplash etc.)'),
        ),
    ]
