# Generated by Django 6.0.4 on 2026-08-04 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_add_tntg_tv_programs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('shopping', 'T&TG Shopping Platform'), ('loyalty', 'Loyalty & Rewards'), ('trade', 'Import & Export Trade'), ('forex', 'Live Forex & Currency'), ('onboarding', 'Platform Onboarding'), ('coffee', 'Coffee Knowledge')], max_length=20)),
                ('description', models.TextField()),
                ('agenda', models.TextField(blank=True, help_text='Line-by-line agenda items')),
                ('event_date', models.DateTimeField()),
                ('duration_mins', models.IntegerField(default=60)),
                ('capacity', models.IntegerField(default=100)),
                ('is_free', models.BooleanField(default=True)),
                ('price_points', models.IntegerField(default=0, help_text='Cost in T&TG Loyalty Points (0 = free)')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/stream link unlocked after registration')),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='confirmed', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='training.trainingevent')),
            ],
        ),
    ]
